-- Active: 1679574137028@@151.161.91.21@3306@znb34_GamerDatabase

/* TABLE FOR THE USERS */
CREATE OR REPLACE TABLE USER()
    USER_ID             SMALLINT(5),
    USER_LNAME          VARCHAR(15),
    USER_FNAME          VARCHAR(15),
    USER_PHONE          char(12),
    USER_EMAIL          char(25),
    USER_GAMERTAG       char(25),
    USER_GAMES_ID       SMALLINT(5),
    USER_FRIENDS_ID     SMALLINT,
    USER_BLOCKS_ID      SMALLINT,
    CHAT_ID             SMALLINT,

    PRIMARY KEY (USER_ID),
    FOREIGN KEY (USER_GAMES_ID) REFERENCES USER_GAMES(USER_GAMES_ID)
);

ALTER TABLE `USER`
    MODIFY USER_PHONE char(12)
;
INSERT
    INTO USER (`USER_ID`, `USER_LNAME`, `USER_FNAME`, `USER_PHONE`, `USER_EMAIL`,
     `USER_GAMERTAG`, `USER_GAMES_ID`, `USER_FRIENDS_ID`,`USER_BLOCKS_ID`, `CHAT_ID`)
    VALUES(12545, "Smith", "John", "814-555-6969", "smithjohn23@gmail.com", "johnsmith69420",85854,12346,12347,12348)
    VALUES(23431, "Johnson", "James","570-555-4200","johnsonjames55@hotmail.com","jamesgames55",90872,25362,76475,35251)
    VALUES(97241, "Williams", "Robert","670-555-1234","williamsrobert99@gmail.com","realrobert500",52356,63426,73748,25210)
    VALUES(78414, "Brown", "David","717-555-0909","browndavid88@gmail.com","dbrown007",62362,84268,90877,78213)
    VALUES(98124, "Jones", "William","814,555-3030","joneswilliam77@hotmail.com","wetwilly11",87712,64555,51515,81246)
    ;

/* TABLE FOR THE USERS FRIENDS */
CREATE OR REPLACE TABLE USER_FRIENDS(
    USER_FRIENDS_ID     SMALLINT,
    USER_ID             SMALLINT,

    PRIMARY KEY(USER_FRIENDS_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID)
);
    INSERT 
        INTO `USER_FRIENDS` (`USER_FRIENDS_ID`, `USER_ID`)
        VALUES (12346, 12545)
        VALUES (23431, 25362)
        VALUES (97241, 63426)
        VALUES (78414, 84268)
        VALUES (98124, 64555)
        ;
/* TABLE FOR USER GAMES LIST */
CREATE OR REPLACE TABLE USER_GAMES(
    USER_GAMES_ID       SMALLINT,
    GAME_ID             SMALLINT,
    PLATFORM_ID         SMALLINT,

    PRIMARY KEY(USER_GAMES_ID),
    FOREIGN KEY(GAME_ID) REFERENCES GAME(GAME_ID),
    FOREIGN KEY(PLATFORM_ID) REFERENCES PLATFORM(PLATFORM_ID)
);

/* TABLE FOR GAME */
CREATE OR REPLACE TABLE GAME(
    GAME_ID         SMALLINT,
    PLATFORM_ID     SMALLINT,
    GAME_TITLE      char(25),
    GAME_GENRE      char(20),
    RELEASE_DATE    DATE,
    AVG_RATING      DECIMAL(2,1),

    PRIMARY KEY (GAME_ID),
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (PLATFORM_ID)
);

/* TABLE FOR PLATFORM */
CREATE OR REPLACE TABLE PLATFORM(
    PLATFORM_ID             SMALLINT,
    USER_ID                 SMALLINT,
    PLATFORM_GAMELIST_ID    SMALLINT,

    PRIMARY KEY (PLATFORM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

/* TABLE FOR FORUM */
CREATE OR REPLACE TABLE FORUM(
    FORUM_ID        SMALLINT,
    USER_ID         SMALLINT,
    GAME_ID         SMALLINT,
    PLATFORM_ID     SMALLINT,
    DATE_POSTED     DATE,

    PRIMARY KEY (FORUM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME (GAME_ID),
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (PLATFORM_ID)
);

/* TABLE FOR THE BLOCKED USERS */
CREATE OR REPLACE TABLE USER_BLOCKS(
    USER_BLOCKS_ID      SMALLINT,
    USER_ID             SMALLINT,

    PRIMARY KEY(USER_BLOCKS_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

/* TABLE FOR THE USER'S CHAT */
CREATE OR REPLACE TABLE CHAT(
    CHAT_ID         SMALLINT,
    MESSAGE_ID      SMALLINT,
    USER_ID         SMALLINT,
    MESSAGE_CONTENT char(255),

    PRIMARY KEY (CHAT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

/* TABLE FOR USER CREATED REVIEWS */
CREATE OR REPLACE TABLE REVIEW(
    REVIEW_ID           SMALLINT,
    USER_ID             SMALLINT,
    GAME_ID             SMALLINT,
    RATING              DECIMAL(2,1),
    REVIEW_CONTENT      char(255),
    DATE_POSTED         DATE,

    PRIMARY KEY (REVIEW_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

/* TABLE FOR USER CREATED POSTS */
CREATE OR REPLACE TABLE POST(
    USER_POST_ID    SMALLINT,
    USER_ID         SMALLINT,
    POST_CONTENT    char(255),

    PRIMARY KEY(USER_POST_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);